version: 0.2
env:
    variables:
        BALANCER_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/beethovenx-optimism'
        MASTERCHEF_SUBGRAPH: 'https://#/'
        BLOCKS_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/optimism-blocks'
        BEETS_BAR_SUBGRAPH: 'https://#/'
        YEARN_VAULTS_ENDPOINT: 'https://#/'
        CHANGELOG_SUBGRAPH: 'https://#/'
        GAUGE_SUBGRAPH: 'https://api.thegraph.com/subgraphs/name/beethovenxfi/balancer-gauges-optimism'
phases:
    install:
        commands:
            - yarn install
    build:
        commands:
            - yarn generate
            - yarn prisma generate
            - yarn prisma migrate deploy
            - yarn build
    post_build:
        commands:
            - echo Build completed on `date`
#      - echo Pushing to graph cdn
#      - npx graphcdn push
cache:
    paths:
        - 'node_modules/**/*'
artifacts:
    files:
        - node_modules/**/*
        - package.json
        - dist/**/*
        - Procfile
        - cron.yaml
        - .platform/**/*
